services:
  client:
    build: ./client
    ports:
      - 8080:8080
    environment:
      - SERVER_UTXO_URI=http://server:7000/utxos=value

  server:
    build: ./server
    ports:
      - 7000:7000
